fix(ci): improve security

diff --git a/.github/workflows/publish-to-mozilla.yml b/.github/workflows/publish-to-mozilla.yml
--- a/.github/workflows/publish-to-mozilla.yml
+++ b/.github/workflows/publish-to-mozilla.yml
@@ -10,21 +10,27 @@ jobs:
   publish-firefox-extension:
     runs-on: ubuntu-latest
     steps:
+      - name: Check Initiating User
+        if: github.actor != 'JayBeeDe'
+        run: |
+          echo "::error title=Unauthorized Access::User ${GITHUB_ACTOR} is not authorized."
+          exit 1
+      - name: Install packages (1/2)
+        run: sudo apt-get install -y curl git jq
       - name: Check out repository
         uses: actions/checkout@v4
         with:
           fetch-depth: 0
-      - name: Install packages
-        run: sudo apt-get install -y coreutils git jq npm
-      - name: Install web-ext
-        run: npm install -g web-ext
       - name: Check tag
         run: |
           set -euo pipefail
           source "${GITHUB_WORKSPACE}/.github/workflows/mozilla_libs.sh"
           TAG="${GITHUB_REF##*/}"
           if [ "$GITHUB_REF_TYPE" == "branch" ]; then
-          TAG="caml_v0.0.1"
+            TAG="caml_v0.0.1"
+          elif !git tag -v "$TAG" > /dev/null 2>&1; then
+            echo "::error::Tag '$TAG' is not signed or could not be verified."
+            exit 1
           fi
           checkTag "$TAG"
       - name: Set version
@@ -32,6 +38,10 @@ jobs:
           set -euo pipefail
           source "${GITHUB_WORKSPACE}/.github/workflows/mozilla_libs.sh"
           setVersion
+      - name: Install packages (2/2)
+        run: sudo apt-get install -y npm
+      - name: Install web-ext
+        run: npm install -g web-ext
       - name: Check extension
         run: |
           set -euo pipefail
