fix(ci): prevent non-authorized users to trigger action

diff --git a/.github/workflows/publish-to-mozilla.yml b/.github/workflows/publish-to-mozilla.yml
--- a/.github/workflows/publish-to-mozilla.yml
+++ b/.github/workflows/publish-to-mozilla.yml
@@ -10,6 +10,11 @@ jobs:
   publish-firefox-extension:
     runs-on: ubuntu-latest
     steps:
+      - name: Check Initiating User
+        if: github.actor != 'JayBeeDe'
+        run: |
+          echo "::error title=Unauthorized Access::User ${GITHUB_ACTOR} is not authorized."
+          exit 1
       - name: Check out repository
         uses: actions/checkout@v4
         with:
